### ISSUE TITLE
unable to pip install 

### ISSUE THREAD

**Issue by thevlab** [Undertone0809/cushy-serial#4]
I got this error. Can you help on this?

Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-LmUOTM/cushy-serial/setup.py", line 19, in <module>
        long_description = (here / "README.md").read_text(encoding="utf-8")
    AttributeError: 'PosixPath' object has no attribute 'read_text'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-LmUOTM/cushy-serial/

**Comment by thevlab** [comment]
my bad. use a wrong python version. issue closed

**Comment by Undertone0809** [comment]
Can I know your python version?

**Comment by thevlab** [comment]
V2.7

**Comment by thevlab** [comment]
> Can I know your python version?

2.7. May I know how to send in binary form?

**Comment by Undertone0809** [comment]
I am sorry, current cushy-serial can not support python v2.7. If possible, try to keep the Python version above 3.7 as much as possible.

But it seems to support version 2.7. You can try git clone code locally and see if it can be run using Python 2.7.

Looking forward to your feedback

**Comment by thevlab** [comment]
> I am sorry, current cushy-serial can not support python v2.7. If possible, try to keep the Python version above 3.7 as much as possible.
> 
> But it seems to support version 2.7. You can try git clone code locally and see if it can be run using Python 2.7.
> 
> Looking forward to your feedback

no worries! it working fine with 3.7!  May I know how to send in binary form?

**Comment by Undertone0809** [comment]
Here is an example:

```python
from cushy_serial import CushySerial

serial = CushySerial("COM1", 9600)
binary_data = bytes([0x01, 0x02, 0x03])
serial.send(binary_data)

```
